spring.application.name=finance-dashboard
spring.config.import=optional:file:.env[.properties]

# ================= DATABASE =================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ================= JWT =================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ================= SWAGGER =================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# default paths (no context path now)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===========  Rate Limit Configuration ============
ratelimit.ip.max-requests=50
ratelimit.ip.window-ms=60000

ratelimit.login.max-requests=5
ratelimit.login.window-ms=60000

#http://localhost:8080/swagger-ui/index.html
#http://localhost:8080/v3/api-docs

server.port=${PORT:8080}